language: rust
branches:
  only:
  - master
matrix:
  include:
    - name: "stable rust"
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo build
        - cargo test
    - name: "nightly rust + rustfmt"
      rust: nightly
      before_script:
        - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      script:
        - cargo fmt -- --check
        - cargo build
        - cargo test
  allow_failures:
    - name: "stable rust"
